victoire_core:
    widgets:
        archive:
            class: "Victoire\\Widget\\ArchiveBundle\\Entity\\WidgetArchive"
            name: Archive

jms_translation:
    configs:
        victoire_archive_bundle:
            dirs: ["@VictoireWidgetArchiveBundle"]
            output_dir: "@VictoireWidgetArchiveBundle/Resources/translations"
