services:
    victoire_core.twig.widget_archive_manager:
        class: Victoire\ArchiveBundle\Widget\Manager\WidgetArchiveManager
        arguments: [@service_container]

    widget_archive_manager:
        alias: victoire_core.twig.widget_archive_manager
