services:
    victoire_core.widget_menu_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Archive }

    #alias to the form
    victoire.widget.form.archive:
        class: Victoire\Widget\ArchiveBundle\Form\WidgetArchiveType
        tags:
            - { name: form.type , alias: victoire_widget_form_archive}

